In [1]:
import numpy as np
import time

## Find the sum of a list of numbers
- Use a for loop
- Use np.sum()

In [14]:
%%timeit -n 20
nums = [1] * 1_000_000

sum_val = 0
for i in range(1_000_000):
    sum_val += nums[i]


30.2 ms ± 2.11 ms per loop (mean ± std. dev. of 7 runs, 20 loops each)


In [13]:
%%timeit -n 20
nums = np.ones(1_000_000)

sum_val = np.sum(nums)

933 µs ± 171 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


## Find the maximum value in an array
- Use a for loop
- Use np.amax()

In [8]:
list_of_nums = np.arange(100000)
np.random.shuffle(list_of_nums)
list_of_nums

array([73928, 44441, 44348, ..., 19766, 86638, 60231])

In [9]:
# For loop
tic = time.time()
max_val = -1

for i in range(100000):
    if list_of_nums[i] > max_val:
        max_val = list_of_nums[i]

toc = time.time()
for_loop_time = toc - tic
print('Using a for loop it took {}s and the maximum value is {}'.format(for_loop_time, max_val))

# Using numpy.amax()
tic = time.time()
max_val = np.amax(list_of_nums)
toc = time.time()

np_sum_time = toc - tic

print('Using np.sum() it took {}s and the maximum value is {}'.format(np_sum_time, max_val))

print('np.amax() is {} times faster'.format(for_loop_time/np_sum_time))

Using a for loop it took 0.028573036193847656s and the maximum value is 99999
Using np.sum() it took 0.00026535987854003906s and the maximum value is 99999
np.amax() is 107.6765498652291 times faster


## Add two vectors
- Use a for loop
- directly add two vectors

In [11]:
list_of_nums1 = np.arange(100000)
list_of_nums2 = np.arange(100000)

# For loop
tic = time.time()
sol = np.empty((100000, 1))

for i in range(100000):
    sol[i] = list_of_nums1[i] + list_of_nums2[i]

toc = time.time()

for_loop_time = toc - tic
print('Using a for loop it took {}s'.format(for_loop_time))

# Vectorize adding
tic = time.time()
sol = list_of_nums1 + list_of_nums2
toc = time.time()

vec_time = toc - tic
print('Using np.sum() it took {}s'.format(vec_time))

print('Vectorize adding is {} times faster'.format(for_loop_time/vec_time))

Using a for loop it took 0.15001702308654785s
Using np.sum() it took 0.00061798095703125s
Vectorize adding is 242.75347222222223 times faster


In [15]:
np.empty([20], int)


array([                  0,                   0,                1568,
                5235653632,                8192,                   0,
                         0,                  35,                   0,
            35871566856192, 5572452859464646656,                   0,
                         0,                  -1,    -105553117233217,
       5572452860762084442,     105553117233288,                   0,
                         0,                   0])

In [111]:
import random


In [144]:
x = np.zeros(10)
print(id(x))
del x


4550958256


In [156]:
a = np.empty(10, int)
a[np.random.randint(0, 10)] = np.random.randint(0, 10)
print(a)
print(id(a))
del a


[8 0 0 2 5 0 0 0 7 5]
4548928368
